logging:
  level: INFO
  loggers:
    com.calebmoviehouse.getvideos: DEBUG
server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001